### ISSUE TITLE
Mubi pages have changed

### ISSUE THREAD

**Issue by choffee** [jbaiter/plugin.video.mubi#5]
Hi, I think the MUBI pages have changed. I get the following error when trying to use the plugin. I don't think there is an 'a' with the class avatar any more.

18:39:59 T:2924469056   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.xbmc/addons/plugin.video.mubi/addon.py", line 16, in <module>
                                                plugin.get_setting("password"))
                                              File "/home/xbmc/.xbmc/addons/plugin.video.mubi/resources/lib/mubi.py", line 585, in login
                                                "a", {"class": "user_avatar"}).get("href").split("/")[-1]
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--

**Comment by jbaiter** [comment]
Sorry for not responding to this earlier, but I didn't have a MUBI subscription for the last few months. I just re-subscribed and will look into the issue once I find some space in my schedule for it :-)

**Comment by choffee** [comment]
Hi,
Really sorry I forgot to update this. It turned out I had not responded to the confirmation email and that was causing the error. It's working fine since I finished that.

I suppose you could say that it should handle that state but it's not that bad a thing.

Thanks

john

**Comment by jbaiter** [comment]
You're right, the module should handle that gracefully and throw a proper Exception that applications can work with.
